MODEL_PROFILES = {
    "best_stable_v1": {
        "description": (
            "Most stable hidden-validation recipe so far: DINOv3 ViT-B encoder, "
            "task-specific FPN, challenge_v1 head widths, uniform decoder/adapter, "
            "grouped split, baseline augmentation, and server_proxy_v1 checkpointing."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "uniform",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.0,
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "uniform",
        },
    },
    "hidden_localrefine_ft_v1": {
        "description": (
            "Best stable hidden-transfer recipe with task-specific local image-detail "
            "adapters enabled. This reruns the earlier promising localrefine path after "
            "fixing adapter optimizer registration."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "localrefine_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.0,
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "localrefine_v1",
        },
    },
    "hidden_context_ft_v1": {
        "description": (
            "Best stable hidden-transfer recipe with residual context adapters enabled. "
            "This is the post-fix rerun of the earlier coarse_refine adapter line."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "coarse_refine_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.0,
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "coarse_refine_v1",
        },
    },
    "hidden_context_measure_v1": {
        "description": (
            "Winning hidden-context adapter family with conservative targeted measurement "
            "supervision on geometry-sensitive tasks only."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "coarse_refine_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.01,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.10,
                "HC": 1.20,
                "IVC": 1.40,
                "PLAX": 0.80,
                "fetal_femur": 0.80,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "coarse_refine_v1",
        },
    },
    "hidden_context_experts_measure_v1": {
        "description": (
            "Context-expert adapter upgrade over the winning hidden-context family, keeping "
            "the same soft targeted measurement supervision while routing hard cardiac tasks "
            "to a stronger expert branch."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_experts_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.15,
                "IVC": 1.30,
                "PLAX": 0.70,
                "fetal_femur": 0.70,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_experts_v1",
        },
    },
    "hidden_context_local_measure_v1": {
        "description": (
            "Hybrid hidden-transfer base model that keeps the winning residual context path "
            "and adds task-specific image-detail correction before the heatmap heads."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.15,
                "IVC": 1.30,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.0,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "uniform",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_geometry_family_v2": {
        "description": (
            "Geometry-first hidden-transfer model: cardiac graph decoding for chamber views, "
            "axis/ellipse coarse-to-fine decoding for abdomen and head, and ridge/strip "
            "specialized decoding for vessel, FUGC, and femur, all on top of the context-local base."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "geometry_family_v2",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.05,
                "HC": 1.20,
                "IVC": 1.40,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "geometry_family_v2",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_hcivc_v1": {
        "description": (
            "Conservative follow-up to the best hidden hybrid base: keep the context-local "
            "adapter, then strengthen only HC and IVC with coarse-to-fine geometry-aware decoders."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_a4c_hcivc_v1": {
        "description": (
            "Second-stage hidden-transfer follow-up to the best HC/IVC-refined model, adding "
            "an A4C structural graph-refinement decoder while keeping the successful hybrid base."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_a4c_hcivc_proxy_v3": {
        "description": (
            "Hidden-transfer selection variant of the best A4C/HC/IVC + context-local family, "
            "keeping the same architecture but choosing checkpoints with a hidden-aware proxy "
            "that emphasizes HC, femur, PSAX, FA, AOP, and A4C."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v3",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "vitlarge_hidden_context_local_a4c_hcivc_v1": {
        "description": (
            "ViT-L backbone branch of the best hidden-transfer family: task-specific FPN, "
            "A4C/HC/IVC refined decoders, and context-local adapters under grouped server-oriented training."
        ),
        "train": {
            "encoder_name": "vit_large_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_large_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_plax_headonly_v1": {
        "description": (
            "Third-stage hidden-transfer follow-up to the best A4C/HC/IVC recipe, replacing "
            "only the PLAX head with a dedicated long-axis decoder for targeted head-only fine-tuning."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_plax_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.90,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_plax_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_fugc_headonly_v2": {
        "description": (
            "Third-stage hidden-transfer follow-up to the best A4C/HC/IVC recipe, replacing "
            "only the FUGC head with the dedicated FUGC segment-and-refine decoder for targeted head-only fine-tuning."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_offset128_v1": {
        "description": (
            "Higher-resolution subpixel model: DINOv3 ViT-B with task-specific FPN, "
            "context-local adapters, proven A4C/HC/IVC/FUGC specialized heads, and "
            "offset-refined deep heads for remaining tasks trained with 128x128 heatmaps."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_texture_offset128_v1": {
        "description": (
            "Dual-stream ultrasound texture extension of offset128_v1. It keeps the same "
            "DINOv3 ViT-B, task-specific FPN, 128x128 heatmaps, and offset heads, but "
            "replaces the context-local adapter with a texture-context adapter that fuses "
            "raw image detail and Sobel edge evidence into the task features."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_context_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_context_v1",
        },
    },
    "hidden_context_texture_residual_offset128_v1": {
        "description": (
            "Load-compatible texture residual extension of offset128_v1. It keeps the "
            "warm-started context-local adapter intact and adds a zero-initialized "
            "ultrasound texture/Sobel residual stream so training begins from the old "
            "solution instead of relearning the adapter."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_residual_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_residual_v1",
        },
    },
    "hidden_context_texture_residual_offset128_v2": {
        "description": (
            "Conservative task-gated texture residual extension of offset128_v1. It "
            "keeps the warm-started context-local pathway intact and adds a small "
            "per-task gated ultrasound texture/Sobel residual stream for controlled "
            "domain-shift adaptation."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_residual_v2",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "texture_residual_v2",
        },
    },
    "hidden_context_structure_v1": {
        "description": (
            "Structure-aware extension of offset128_v1. It keeps the best 128x128 hidden-context "
            "recipe and adds an auxiliary anatomy-structure map branch so each task learns a "
            "line, contour, shaft, or cardiac-view support map in addition to point heatmaps."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "structure_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.10,
            "fugc_segment_loss_weight": 0.05,
            "ivc_band_loss_weight": 0.05,
            "structure_loss_weight": 0.05,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "structure_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_offset192_v1": {
        "description": (
            "Controlled follow-up to offset128_v1. It keeps the same hidden-context "
            "architecture and learned offset heads, but raises the heatmap target to "
            "192x192 with a matched Gaussian sigma."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [192, 192],
            "heatmap_sigma": 4.2,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_offset256_v1": {
        "description": (
            "Controlled high-resolution follow-up to offset128_v1. It keeps the same "
            "hidden-context architecture and learned offset heads, but raises the heatmap "
            "target to 256x256 with a matched Gaussian sigma."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [256, 256],
            "heatmap_sigma": 5.6,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_offset128_crop_panel_v1": {
        "description": (
            "Offset128 hidden-context model with cardiac split-screen normalization. "
            "Detected split-screen cardiac training rows are cropped to the landmark-containing "
            "panel instead of being kept as two-panel images or discarded."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "crop_panel",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_offset128_v2": {
        "description": (
            "Conservative follow-up to offset128_v1: keep the 128x128 heatmaps and "
            "offset-refined dense heads, then add zero-started post-offset correction "
            "only to HC and IVC."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "heatmap_size": [128, 128],
            "heatmap_sigma": 2.8,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v2",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_fugc_offset_v2",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_fugc_fa_a4cv2_v1": {
        "description": (
            "Structured A4C-upgrade branch on top of the best hidden-transfer family, keeping "
            "the proven FUGC/FA path while replacing only the A4C decoder with a stronger "
            "group-aware graph-plus-local refinement head."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv2_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv2_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_fugc_fa_a4cv3_v1": {
        "description": (
            "Residual A4C-upgrade branch on top of the best hidden-transfer family, keeping "
            "the proven FUGC/FA path while replacing only the A4C decoder with a checkpoint-compatible "
            "graph decoder plus small local residual refinement."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv3_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv3_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_fugc_fa_a4cv4_v1": {
        "description": (
            "Stronger residual A4C-upgrade branch on top of the best hidden-transfer family, keeping "
            "the proven FUGC/FA path while replacing only the A4C decoder with a checkpoint-compatible "
            "multiscale residual heatmap and stronger local refinement head."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv4_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.75,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4cv4_hc_ivc_fugc_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
    "hidden_context_local_femur_headonly_v1": {
        "description": (
            "Third-stage hidden-transfer follow-up to the best A4C/HC/IVC recipe, replacing "
            "only the fetal femur head with the dedicated shaft-aware decoder for targeted head-only fine-tuning."
        ),
        "train": {
            "encoder_name": "vit_base_patch16_dinov3",
            "input_size": 512,
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "head_type": "deep",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_femur_refine_v1",
            "task_adapter_profile": "context_local_v1",
            "task_loss_family_profile": "uniform",
            "split_mode": "grouped",
            "augmentation_profile": "baseline",
            "checkpoint_score_mode": "server_proxy_v1",
            "cardiac_split_screen_mode": "keep",
            "measurement_loss_weight": 0.008,
            "measurement_loss_tasks": ["FA", "HC", "IVC", "PLAX", "fetal_femur"],
            "measurement_task_weight_overrides": {
                "FA": 1.00,
                "HC": 1.20,
                "IVC": 1.45,
                "PLAX": 0.75,
                "fetal_femur": 0.95,
            },
            "dataset_loss_weight": 0.0,
            "femur_shaft_loss_weight": 0.15,
            "fugc_segment_loss_weight": 0.08,
            "ivc_band_loss_weight": 0.08,
        },
        "inference": {
            "encoder_name": "vit_base_patch16_dinov3",
            "use_fpn": True,
            "fpn_mode": "task_specific",
            "fpn_type": "fpn",
            "task_head_profile": "challenge_v1",
            "task_decoder_profile": "hidden_a4c_hc_ivc_femur_refine_v1",
            "task_adapter_profile": "context_local_v1",
        },
    },
}

MODEL_PROFILE_NAMES = tuple(sorted(MODEL_PROFILES.keys()))


def get_model_profile(profile_name: str) -> dict:
    if profile_name not in MODEL_PROFILES:
        raise ValueError(f"Unsupported model profile: {profile_name}")
    return MODEL_PROFILES[profile_name]


def apply_model_profile(profile_name: str, stage: str, current_config: dict) -> dict:
    profile = get_model_profile(profile_name)
    if stage not in profile:
        raise ValueError(f"Profile '{profile_name}' does not define stage '{stage}'")
    merged = dict(current_config)
    merged.update(profile[stage])
    return merged
